[NEW] Rust Blinky Lights Workshop
Hyp-ed/workshops-2025 pull request #4
Opened 2024-09-17 17:07 UTC by davidbeechey

Workshop intended to be run _after_ the "Getting Started with Rust" workshop as an introduction to writing embedded Rust.

2024-09-18 10:05 UTC, kshxtij requested changes
LGTM, i spotted a type but just run a spell check just in case tbh

2024-09-18 10:05 UTC, kshxtij commented on 03-rust_blinky_lights/README.md
> +This creates a new `Ouput` struct, which represents a GPIO pin that can be written to. The first argument is the pin, the second is the initial state of the pin, and the third is the speed of the pin
Output

2024-09-18 11:20 UTC, TomLonergan03 approved these changes
very nice

2024-10-03 09:36 UTC, licornes-fluos approved these changes
Seems great

2024-10-03 11:20 UTC, merged